# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-07 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OauthApp',
        ),
    ]
